use std::fs;
use std::path::Path;

const C_TO_RAK: &[(&str, &str)] = &[
    ("char", "string"),
    ("void", "nil"),
    ("int", "i32"),
    ("unsigned int", "u32"),
    ("short", "i16"),
    ("unsigned short", "u16"),
    ("long", "i64"),
    ("unsigned long", "u64"),
    ("long long", "i64"),
    ("unsigned long long", "u64"),
    ("float", "f32"),
    ("double", "f64"),
    ("bool", "bool"),
    ("size_t", "u64"),
    ("uint8_t", "u8"),
    ("uint16_t", "u16"),
    ("uint32_t", "u32"),
    ("uint64_t", "u64"),
    ("int8_t", "i8"),
    ("int16_t", "i16"),
    ("int32_t", "i32"),
    ("int64_t", "i64"),
    ("_Bool", "bool"),
];

pub fn generate(header: &str, output: &str) -> Result<(), String> {
    let header_path = Path::new(header);
    if !header_path.exists() {
        return Err(format!("header not found: {}", header));
    }
    let source = fs::read_to_string(header_path).map_err(|e| e.to_string())?;

    let funcs = parse_functions(&source);
    let structs = parse_structs(&source);

    let mut rak = String::new();
    rak.push_str(&format!("// Generated by rakc bindgen from {}\n", header));
    rak.push_str("// C functions callable from Rak via extern_call.\n\n");

    for (name, params, ret) in &funcs {
        let rak_ret = map_type(ret);
        let mut args = String::new();
        let mut cargs = String::new();
        for (pname, ptype) in params {
            if !args.is_empty() {
                args.push_str(", ");
            }
            args.push_str(&format!("{}: {}", pname, map_type(ptype)));
            if !cargs.is_empty() {
                cargs.push_str(", ");
            }
            cargs.push_str(pname);
        }
        rak.push_str(&format!("fn {}({}) -> {} {{\n", name, args, rak_ret));
        rak.push_str(&format!("    return extern_call(\"{}\"{})\n", name, if cargs.is_empty() { String::new() } else { format!(", {}", cargs) }));
        rak.push_str("}\n\n");
    }

    for (sname, fields) in &structs {
        rak.push_str(&format!("struct {} {{\n", sname));
        for (fname, ftype) in fields {
            rak.push_str(&format!("    {}: {}\n", fname, map_type(ftype)));
        }
        rak.push_str("}\n\n");
    }

    if output == "-" {
        println!("{}", rak);
    } else {
        fs::write(output, &rak).map_err(|e| e.to_string())?;
        println!("Generated {} ({} functions, {} structs)", output, funcs.len(), structs.len());
    }
    Ok(())
}

fn map_type(c_type: &str) -> String {
    let t = c_type.trim();
    let t = t.trim_end_matches('*').trim();
    if c_type.trim_end_matches('*').trim() != c_type.trim() {
        return "u64".to_string();
    }
    for (c, r) in C_TO_RAK {
        if t == *c {
            return r.to_string();
        }
    }
    if t.starts_with("uint") || t.starts_with("int") {
        return "i64".to_string();
    }
    t.to_string()
}

fn parse_functions(source: &str) -> Vec<(String, Vec<(String, String)>, String)> {
    let mut funcs = Vec::new();
    let mut in_decl = String::new();
    for line in source.lines() {
        let line = line.trim();
        if line.starts_with("//") || line.starts_with("#") || line.starts_with("/*") {
            continue;
        }
        in_decl.push(' ');
        in_decl.push_str(line);
        let decl = in_decl.trim();
        if decl.ends_with(';') && decl.contains('(') && !decl.starts_with("typedef") && !decl.starts_with("struct") && !decl.starts_with("enum") {
            let decl = decl.trim_end_matches(';').trim();
            if let Some((name, params, ret)) = parse_decl(decl) {
                funcs.push((name, params, ret));
            }
            in_decl.clear();
        } else if decl.ends_with(';') {
            in_decl.clear();
        }
    }
    funcs
}

fn parse_decl(decl: &str) -> Option<(String, Vec<(String, String)>, String)> {
    let open = decl.find('(')?;
    let close = decl.rfind(')')?;
    let head = &decl[..open];
    let args = &decl[open + 1..close];

    let head = head.trim();
    let name_end = head.rfind(|c: char| c.is_alphanumeric() || c == '_').map(|i| i + 1).unwrap_or(head.len());
    let name_start = head[..name_end].rfind(|c: char| !(c.is_alphanumeric() || c == '_')).map(|i| i + 1).unwrap_or(0);
    let name = head[name_start..name_end].to_string();
    if name.is_empty() {
        return None;
    }
    let mut ret = head[..name_start].trim().to_string();
    if let Some(star_idx) = name_start.checked_sub(0) {
        let _ = star_idx;
    }
    ret = ret.trim_end_matches('*').trim().to_string();

    let mut params = Vec::new();
    let args = args.trim();
    if args != "void" && !args.is_empty() {
        for arg in args.split(',') {
            let arg = arg.trim();
            if arg.is_empty() {
                continue;
            }
            let (ptype, pname) = split_param_type_name(arg);
            params.push((pname, ptype));
        }
    }

    Some((name, params, if ret.is_empty() { "void".to_string() } else { ret }))
}

fn split_param_type_name(arg: &str) -> (String, String) {
    let arg = arg.trim();
    let stars = arg.matches('*').count();
    let base = arg.replace('*', " ").trim().to_string();
    let parts: Vec<&str> = base.split_whitespace().collect();
    if parts.is_empty() {
        return ("int".to_string(), "_arg".to_string());
    }
    let name = parts.last().unwrap().trim().to_string();
    let ty_parts = if parts.len() > 1 { &parts[..parts.len() - 1] } else { &[] };
    let ty = ty_parts.join(" ");
    let ty = if ty.is_empty() { "int".to_string() } else { ty };
    let ty = if stars > 0 { "u64".to_string() } else { ty };
    (ty, name)
}

fn parse_structs(source: &str) -> Vec<(String, Vec<(String, String)>)> {
    let mut structs = Vec::new();
    let lines: Vec<&str> = source.lines().collect();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i].trim();
        if line.starts_with("struct ") && !line.ends_with(';') {
            let rest = &line["struct ".len()..];
            if let Some(open_idx) = rest.find('{') {
                let name = rest[..open_idx].trim().to_string();
                let mut fields = Vec::new();
                let mut j = i;
                // scan until matching close brace on this or subsequent lines
                let mut depth = rest.matches('{').count() as i32 - rest.matches('}').count() as i32;
                let mut cur = rest[open_idx + 1..].to_string();
                while depth > 0 {
                    j += 1;
                    if j >= lines.len() {
                        break;
                    }
                    let l = lines[j];
                    depth += l.matches('{').count() as i32 - l.matches('}').count() as i32;
                    cur.push_str(l);
                }
                for f in cur.split(';') {
                    let f = f.trim();
                    if f.is_empty() || f == "}" {
                        continue;
                    }
                    let (t, n) = split_param_type_name(f);
                    if !n.starts_with('_') {
                        fields.push((n, t));
                    }
                }
                if !name.is_empty() {
                    structs.push((name, fields));
                }
                i = j;
            }
        }
        i += 1;
    }
    structs
}