[package]
name = "rakpkg"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Rak package manager"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
anyhow = "1.0"

[lib]
name = "rakpkg"
path = "src/lib.rs"

[[bin]]
name = "rakpkg"
path = "src/main.rs"
